#general params
fractal_type = "julia"
iterations = 16

#simple fractals
scaling = 0.25

#num_sys params
num_sys = 3

#line-based params
base_preset = "square"
custom_lines = [
    [[300, 200], [-300, 200]],
    [[-300, 200], [0, -100]],
    [[0, -100], [300, 200]]
]

line_model_width = 0.65
line_model_height = 4
rotation_angle = 90

#spirals
spiral_angle = 1
spiral_scaling = 1.02

#logistic
l_trash_iterations = 400
l_samples = 20
l_x0 = 0.001
l_y0 = 0.001
l_stepsize = 0.0001
l_a_start = 2
l_a_end = 4

#point_fractals
p_iterations = 300
a = -0.7
b = 0.25

x_start = -2
x_end = 2
x_stepsize = 0.005

y_start = -2
y_end = 2
y_stepsize = 0.005
