#general params
fractal_type = "simple tree"
iterations = 1

#simple fractals
scaling = 0.5

#num_sys params
num_sys = 3

#line-based params
base_preset = "one line"
custom_lines = [
    [[300, 200], [-300, 200]],
    [[-300, 200], [0, -100]],
    [[0, -100], [300, 200]]
]

line_model_width = 0.66
line_model_height = 0.33
rotation_angle = 90